packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@hookform/resolvers": ^5.2.2
  "@radix-ui/react-label": ^2.1.8
  "@radix-ui/react-slot": ^1.2.4
  "@tailwindcss/vite": ^4.2.2
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.577.0
  react: ^19.2.4
  react-dom: ^19.2.4
  react-hook-form: ^7.71.2
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: ^4.3.6

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
